### ISSUE TITLE
window is undefined error during Angular 17 SSR prerendering

### ISSUE THREAD

**Issue by timtim5174** [PiwikPRO/ngx-piwik-pro#24]
Hello, 

first of all: since I don't write issue reports so often on public projects, I apologize if I don't follow a formal process. 

Currently I'm working on an Angular 17 website with SSR prerendering. Since your latest package update (v1.1.0) I'm getting the error `window is undefined` during `npm build`.

I guess it belongs to this [line of code](https://github.com/PiwikPRO/ngx-piwik-pro/commit/0501f9d885dbb1a709487a80ba9799776ba53b4c#diff-6ce11ca2076c05d9f23ff6732741bdf36dc72d56f4fb4f39f9fefd850784ac11R20) in your latest change.

However, merging this [PR](https://github.com/PiwikPRO/ngx-piwik-pro/pull/18) and solving the merge conflict should fix it.

v1.0.2 works fine

**Comment by danieltwork** [comment]
Hi @timtim5174 , we have released a new version to fix your problem, could you verify in your environment if version 1.1.1 fixes your problem and you are satisfied?

**Comment by timtim5174** [comment]
Hey @danieltwork thanks for your quick response. I've updated my version to 1.1.1, but the error still exist during build.  Probably there is still a missing unchecked window reference in the code.
